[project]
name = "resume"
description = "My personal resume"
version = "0.1.0"
authors = [
    {name = "Axel H.", email = "noirbizarre@gmail.com"},
]
requires-python = "==3.14.*"
dependencies = [
    "cyclopts>=4.2.3",
    "jinja2>=3.1.6",
    "markdown-it-py[linkify,plugins]>=4.0.0",
    "pyyaml>=6.0.0",
    "rich>=14.2.0",
    "weasyprint>=66.0",
    "pydantic>=2.0.0",
]

[project.urls]

[project.scripts]
resume = "resume.__main__:app"

[dependency-groups]
dev = [
    "livereload<3.0.0,>=2.6.3",
]

[build-system]
requires = ["uv_build>=0.9.9,<0.10.0"]
build-backend = "uv_build"
